name: npm-test

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  npm-test:
    uses: parkerbxyz/.github/.github/workflows/npm-test.yml@main
