---
name: Release

on:
  push:
    branches: [ $default-branch ]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    uses: parkerbxyz/.github/.github/workflows/release-please.yml@main
    with:
      release-type: "simple"
