name: npm-run-build

on:
  workflow_call:
    inputs:
      file-pattern:
        description: "Optional glob pattern of files which should be added to the commit"
        type: string
        default: "."
      commit-message:
        description: "Commit message"
        type: string
        default: "chore: npm run build"

jobs:
  npm-run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.ACTIONS_APP_ID }}
          private-key: ${{ secrets.ACTIONS_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - run: npm ci
      - name: Run build script
        id: build
        run: npm run build
      - name: Commit changes
        if: steps.build.conclusion == 'success'
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7.0.0
        with:
          file_pattern: ${{ inputs.file-pattern }}
          commit_author: "${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>"
          commit_message: ${{ inputs.commit-message }}
