name: release-please

on:
  workflow_call:
    inputs:
      release-type:
        description: "Defines the release strategy to use (e.g., python, node)"
        default: "simple"
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.ACTIONS_APP_ID }}
          private-key: ${{ secrets.ACTIONS_APP_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@c2a5a2bd6a758a0937f1ddb1e8950609867ed15c # v4.3.0
        id: release
        with:
          release-type: ${{ inputs.release-type }}
          token: ${{ steps.app-token.outputs.token }}
      - uses: actions/checkout@v5
        if: steps.release.outputs.release_created == 'true'
        with:
          fetch-tags: true
      - name: Configure Git
        if: steps.release.outputs.release_created == 'true'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Update major version tag
        if: steps.release.outputs.release_created == 'true'
        run: |
          # Update (or create) major version tag to point to the new release
          git tag --force v${{ steps.release.outputs.major }} v${{ steps.release.outputs.version }}
          git push origin v${{ steps.release.outputs.major }} --force
